# coding=utf-8

K_BURN_TICKS_LEFT = "st:burn_ticks_left"


STORE_RF_MAX = 28800
MAX_LAVA_VOLUME = 2000
MAX_WATER_VOLUME = 2000

ONCE_LAVA_REDUCE_VOLUME = 200  # 单次产能熔岩减少的量
ONCE_WATER_REDUCE_VOLUME = 400  # 单次产能耗水量
ONCE_BURNING_TICKS = 100  # 单次产能持续时间
ORIGIN_GENERATED_POWER = 240  # 默认产能
GENERATED_POWER_WITH_WATER = 320  # 耗水产能
LAVA_ID = "minecraft:lava"
WATER_ID = "minecraft:water"
