# coding=utf-8
from ..define.id_enum import METAL_PRESS, Ingots, Sticks
from ..define.id_enum import fluids
from ..mini_jei.core import RecipesCollection
from ..mini_jei.machinery.metal_press import MachineRecipe, MetalPressRecipe

STORE_RF_MAX = 8800
MAX_FLUID_VOLUME = 1000

recipes = RecipesCollection(
    METAL_PRESS,
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        "minecraft:copper_ingot",
        1,
        Sticks.COPPER,
        2,
        tick_duration=60,
        power_cost=40,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        "minecraft:iron_ingot",
        1,
        Sticks.IRON,
        2,
        tick_duration=60,
        power_cost=40,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.TIN,
        1,
        Sticks.TIN,
        2,
        tick_duration=60,
        power_cost=40,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.SILVER,
        1,
        Sticks.SILVER,
        2,
        tick_duration=40,
        power_cost=40,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.PLATINUM,
        1,
        Sticks.PLATINUM,
        2,
        tick_duration=40,
        power_cost=40,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.STEEL,
        1,
        Sticks.STEEL,
        2,
        tick_duration=60,
        power_cost=50,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.BRONZE,
        1,
        Sticks.BRONZE,
        2,
        tick_duration=60,
        power_cost=50,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.INVAR,
        1,
        Sticks.INVAR,
        2,
        tick_duration=60,
        power_cost=50,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.CUPRONICKEL,
        1,
        Sticks.CUPRONICKEL,
        2,
        tick_duration=60,
        power_cost=50,
    ),
    MetalPressRecipe(
        fluids.Common.LUBRICANT,
        10,
        Ingots.SUPERCONDUCT,
        1,
        Sticks.SUPERCONDUCT,
        2,
        tick_duration=60,
        power_cost=50,
    ),
)  # type: RecipesCollection[MachineRecipe]
